language: python
python:
  - "3.6"
install:
  - python setup.py sdist
  - pip install flake8 yapf isort
before_script:
  - flake8
  - isort -rc --diff .
  - yapf -r -d .
script:
  - python setup.py test
